
INSERT INTO public.jobs (title, company, location, industry, type, summary, description, pay, hours, contact, email, requirements) VALUES
(
  '시티 웨스트필드 주방보조',
  'KO-V Korea Street Food',
  ARRAY['시드니 시티'],
  '요식업',
  '풀타임',
  '시드니 시티 타운홀 쇼핑센터에 위치한 한국 TA샵에서 구인합니다. 시급 $26-27 경력에 따른 지급.',
  E'안녕하세요.\n시드니 시티 타운홀 쇼핑센터에 위치한 한국 TA샵에서 구인합니다.\n많은 지원 바랍니다.\n매장 위치: 타운홀 웨스트필드 센터 포인트\n\n1. 모집 분야\n- 주방 주방보조\n\n2. 근무 조건\n. 고용형태: 풀타임\n- 근무시간: 08:00 ~ 16:00 (주5일)\n- 시급: $26-27 경력에 따른 지급.\n- 유니폼, 앞치마, 모자 제공\n- 점심식사, paid 브레이크 타임 제공\n\n3. 자격 요건\n- 호주법상 근무 가능하신 분\n- 성실하고 손이 빠른신분\n- 손님 대응에 자신감 충만한분\n\n3. 지원 방법\n아래 이메일로 간단한 자기소개서 또는 이력서 문자로 보내주시기 바랍니다.\n제목은 성함/성별/나이/비자/경력사항으로 부탁드립니다.\n\n(문자 지원 가능, 전화는 피해주세요)\n문자로 간단한 소개서 보내주시고 메일로 이력서 보내주세요. ^^ 많은 지원 부탁드립니다.\n확인 후 바로 연락드리겠습니다.',
  '시급 $26-27',
  '08:00 ~ 16:00 (주5일)',
  '0433907799',
  'kovcentrepoint@gmail.com',
  ARRAY['호주법상 근무 가능하신 분', '성실하고 손이 빠른신분', '손님 대응에 자신감 충만한분']
),
(
  '시티 소풍 홀서빙 구합니다',
  'Everyday Sopoong',
  ARRAY['시드니 시티'],
  '요식업',
  '풀타임',
  '시티 소풍 한식당에서 홀서빙 직원 모집합니다. 문자로 간단한 소개 보내주시면 연락드릴게요.',
  E'안녕하세요,\n\n시티 소풍 한식당에서 홀서빙 직원 모집합니다.\n\n문자로 간단한 소개 보내주시면 연락드릴게요.',
  NULL,
  NULL,
  '0450727861',
  'jyflsm@naver.com',
  NULL
),
(
  '뉴잉톤 초심 파트타임 키친핸드 구합니다',
  '뉴잉톤 초심',
  ARRAY['뉴잉톤', '로즈'],
  '요식업',
  '파트타임',
  '로즈, 올림픽파크에서 가까이 위치한 뉴잉톤 초심에서 키친핸드 구합니다. 주 5~6일.',
  E'안녕하세요,\n로즈, 올림픽파크에서 가까이 위치한\n''뉴잉톤 초심'' 에서 키친핸드 구합니다.\n\n근무 일정은,\n주 5~6일\n파트타임 10:30 am ~2:30 pm (주5~ 6일)\n        5 pm ~ 9:30 pm (주1~2일)\n\n시급은 면접 후 결정됩니다.\n이력서는 메일로 보내주시거나 면접보러 오실 때 가지고 오시면 됩니다.\n\n문의사항은\n0402 643 145로 연락주시면 됩니다.\n\n많은 지원 부탁드립니다.\n감사합니다.',
  NULL,
  '10:30am-2:30pm (주5~6일), 5pm-9:30pm (주1~2일)',
  '0402643145',
  'sy9473@gmail.com',
  NULL
),
(
  '홀직원 Macarthur Square (Campbelltown)',
  'MakiMoto Japanese Restaurant',
  ARRAY['캠벨타운'],
  '요식업',
  '풀타임',
  'Macarthur Square(Campbelltown)에 위치한 MakiMoto Japanese Restaurant에서 홀 직원(Front of House)을 모집합니다.',
  E'안녕하세요.\nMacarthur Square (Campbelltown)에 위치한 MakiMoto Japanese Restaurant에서홀 직원(Front of House)을 모집합니다.\n\n모집 분야\n• 홀 스태프(주5일 가능자)\n\n자격 요건\n• 밝고 친절한 서비스 마인드를 가진 분\n• 빠른 템포의 레스토랑 환경에서도 즐겁게 일할 수 있는 분\n• 팀워크와 책임감을 갖춘 분\n• 관련 경력자 우대 (경험이 없어도 성실한 분은 환영합니다)\n\n근무 조건\n• 근무 형태: Full-time 또는 고정 Part-time\n• 근무 장소: MakiMoto – Macarthur Square Shopping Centre, Campbelltown NSW 2560\n• 근무 시간: 월요일~일요일 중 스케줄 협의 (Lunch & Dinner)\n• 급여: 법정 최저 이상, 경력 및 능력에 따라 협의\n\n지원 방법\n이력서를 macarthur@makimoto.com.au 로 보내주세요.\n적합한 분께 개별 연락 후 면접을 진행합니다.\n\nwww.makimoto.com.au',
  '법정 최저 이상',
  '월~일 스케줄 협의 (Lunch & Dinner)',
  '0425414650',
  'macarthur@makimoto.com.au',
  ARRAY['밝고 친절한 서비스 마인드를 가진 분', '팀워크와 책임감을 갖춘 분', '관련 경력자 우대']
),
(
  '일식 핫푸드 / Campbelltown',
  'MakiMoto Japanese Restaurant',
  ARRAY['캠벨타운'],
  '요식업',
  '캐주얼',
  'Macarthur Square(Campbelltown)에 위치한 MakiMoto Japanese Restaurant에서 주방 직원(Kitchen Staff)을 모집합니다.',
  E'안녕하세요.\nMacarthur Square (Campbelltown)에 위치한 MakiMoto Japanese Restaurant에서\n책임감 있고 성실한 주방 직원(Kitchen Staff)을 모집합니다.\n일식에 관심이 많고, 빠른 환경 속에서도 팀워크를 가지고 함께 일할 분을 찾고 있습니다.\n\n모집 분야\n• 핫푸드 요리사 (Cook) – 파트타임 / 풀타임 / 캐주얼\n\n자격 요건\n• 일식 또는 아시안 레스토랑 경력자 우대\n• 팀워크와 책임감이 있는 분\n• 빠른 환경에서도 효율적으로 일할 수 있는 분\n• 장기 근무 가능자 우대\n\n근무 조건\n• 근무 형태: 풀타임, 파트타임, 캐주얼 (협의 가능)\n• 근무 장소: MakiMoto – Macarthur Square Shopping Centre, Campbelltown NSW 2560\n• 급여: 법정 최저 이상, 경력과 능력에 따라 협의\n• 적합한 지원자의 경우 비자 스폰서십 제공 가능\n\n지원 방법\n이력서를 macarthur@makimoto.com.au 로 보내주세요.\n\n문의 문자: 0425 414 650\n\n적합한 분께 개별 연락 후 면접을 진행합니다.\n성실하고 열정 있는 분들의 많은 지원 바랍니다.\n\nwww.makimoto.com.au',
  '법정 최저 이상',
  '풀타임/파트타임/캐주얼 협의',
  '0425414650',
  'macarthur@makimoto.com.au',
  ARRAY['일식 또는 아시안 레스토랑 경력자 우대', '팀워크와 책임감이 있는 분', '장기 근무 가능자 우대']
),
(
  '에핑 일식당 (KAZE) 주방보조 구인 금토 저녁파트',
  'Kaze Fresh Sushi',
  ARRAY['에핑'],
  '요식업',
  '파트타임',
  '에핑(Epping)에 위치한 카제 일식집(Kaze Fresh Sushi)에서 주방보조 핫푸드 파트타임 가능자 구합니다. 주방경력 최소 1년 이상.',
  E'안녕하세요\n에핑(Epping)에 위치한 카제 일식집(Kaze Fresh Sushi)에서 주방보조 핫푸드 파트타임 가능자 구합니다.\n주방경력 최소 1년 이상 경력자 원합니다.\n\n*** 일식 핫푸드 주방보조 (파트타임) ***\n\n저녁파트 5시 시작, 8시 반 마감\n금,토 저녁 가능자 (템푸라 파트)\n주방 핫푸드 경력 1년이상 있는 분 원합니다.\n월요일 정기휴무\n\n일식경력 있으면 좋고 없더라도 핫푸드 주방경력 있는 분 원합니다.\n메뉴가 간단해서 경력 있으신 분들은 금방 익숙해집니다.\n*** 일식 템푸라, 설거지, 재료손질 ***\n\n월요일 휴무\n금요일 토요일 저녁파트 급구합니다.\n\n이름/나이/성별/거주지/지원파트/경력유무/비자상태 등을 문자로 보내주시면 연락 드리겠습니다.',
  NULL,
  '저녁 5시~8시반 (금,토)',
  '0487341848',
  'valse64@hotmail.com',
  ARRAY['주방경력 최소 1년 이상', '금,토 저녁 가능자']
),
(
  '자갈치 Lidcombe 주방 이모 구합니다',
  '자갈치 (Jagalchi)',
  ARRAY['리드컴'],
  '요식업',
  '파트타임',
  'Lidcombe에 위치한 자갈치(Jagalchi)에서 주방 이모님을 모집합니다. 주 4일 정도 근무.',
  E'🐙 자갈치 Lidcombe 주방 직원 모집\n\n안녕하세요.\nLidcombe에 위치한 자갈치(Jagalchi)에서 주방 이모님을 모집합니다.\n\n✔️ 근무일수\n주 4일 정도 근무 가능하신 분\n\n✔️ 근무시간\n10:00 AM – 10:00 PM\n(중간 1.5시간 브레이크)\n\n✔️ 우대사항\n한식당 근무 경험 있으신 분 우대\n성실하게 오래 함께 일하실 분 환영합니다\n\n📍 근무지\n2B Vaughan St, Lidcombe NSW 2141\n\n📞 문의 / 지원\n0452 498 804\n궁금하신 점 있으시면 문자 또는 전화 주세요.\n\n많은 지원 부탁드립니다. 감사합니다.',
  NULL,
  '10:00 AM – 10:00 PM (중간 1.5시간 브레이크), 주 4일',
  '0452498804',
  'ethankoo86@gmail.com',
  ARRAY['한식당 근무 경험 있으신 분 우대', '주 4일 근무 가능하신 분']
),
(
  'Admin Officer (CJ 회계법인)',
  'CJ Tax Consulting',
  ARRAY['시드니 시티'],
  '사무/회계',
  '파트타임',
  'CJ 회계법인(CJ Tax Consulting)에서 함께 일할 파트타임 Administrator를 모집합니다. 시급 $25 + Superannuation.',
  E'안녕하세요, 저희 CJ 회계법인(CJ Tax Consulting)에서 함께 일할 파트타임 Administrator를 모집합니다.\n\n주요 업무\nBookkeeping\nFiling\n고객 응대\n기타 행정 업무\n\n근무 조건\n근무 시간: 오전 10시부터 오후 6시까지\n시급: $25 + Superannuation\nProbation 기간: 6개월\n\n지원 자격\n호주에서 비즈니스 관련 전공을 공부 중이거나 졸업하신 분을 우선적으로 선호합니다.\n워킹 홀리데이 비자 소지자는 고용이 어렵습니다.\n\n저희와 함께 성장하며 회계법인의 행정 업무를 경험하고자 하시는 분들의 많은 지원 바랍니다.\n이력서는 ej@cjsolutions.com.au 로 보내 주십시요.\n\n감사합니다!',
  '시급 $25 + Superannuation',
  '오전 10시~오후 6시',
  NULL,
  'ej@cjsolutions.com.au',
  ARRAY['비즈니스 관련 전공 공부 중이거나 졸업하신 분', '워킹 홀리데이 비자 소지자 불가']
);
